{{- if .Values.certificate.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{.Release.Name}}-certificate
  namespace: {{.Release.Namespace}}
spec:
  # Secret names are always required.
  secretName: {{.Values.certificate.secret.name | default (printf "%s-tls" .Release.Name) }}
{{- if not (empty .Values.certificate.secret.annotations) }}
  secretTemplate:
    annotations:
{{ .Values.certificate.secret.annotations | toYaml | indent 6 }}
{{- end }}
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
      - 3sIT
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  # At least one of a DNS Name, URI, or IP address is required.
  dnsNames:
{{ toYaml .Values.domains | indent 4 }}
  # Issuer references are always required.
  issuerRef:
    name: {{.Values.certificate.issuer }}
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: ClusterIssuer
{{- end }}