{{- if .Values.gateway.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{.Values.gateway.name | default (printf "%s-gateway" .Release.Name) }}
  namespace: {{.Release.Namespace}}
spec:
  selector:
    ingress: {{ .Values.controller }}
  servers:
  - port:
      number: {{.Values.gateway.https.port}}
      name: https
      protocol: HTTPS
    hosts:
{{ toYaml .Values.domains | indent 6}}
    tls:
      mode: SIMPLE # enables HTTPS on this port
      credentialName: {{.Values.certificate.secret.name | default (printf "%s-tls" .Release.Name) }} # fetches certs from Kubernetes secret
  - port:
      number: {{.Values.gateway.http.port}}
      name: http
      protocol: HTTP
    tls:
      httpsRedirect: true
    hosts:
{{ toYaml .Values.domains | indent 6}}
{{- end }}