apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{.Values.name | default (printf "%s-gateway" .Release.Name) }}
  namespace: {{.Release.Namespace}}
spec:
  selector:
    ingress: ext
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - '*'
    tls:
      mode: SIMPLE # enables HTTPS on this port
      credentialName: {{.Values.certificate.secret.name | default (printf "%s-tls" .Release.Name) }} # fetches certs from Kubernetes secret
  - port:
      number: 80
      name: http
      protocol: HTTP
    tls:
      httpsRedirect: true
    hosts:
    - '*'