apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-vs
spec:
  gateways:
    - {{.Values.gateway.name | default (printf "%s-gateway" .Release.Name) }}
  hosts:
{{ toYaml .Values.domains | indent 4 }}
{{- if and (not (empty .Values.redirect.from)) (gt (len .Values.redirect.to) 0) }}
{{ toYaml .Values.redirect.from | indent 4 }}
{{- end }}
  http:
    - match:
        {{- range .Values.domains }}
        - authority:
            exact: {{ . }}
        {{- end }}
        - uri:
            prefix: {{ .Values.service.path }}
      route:
        - destination:
            host: {{ .Values.service.name }}
            port:
              number: {{ .Values.service.port }}
{{- if and (not (empty .Values.redirect.from)) (gt (len .Values.redirect.to) 0) }}
    - match:
      {{- range .Values.redirect.from }}
      - authority:
          exact: {{ . }}
      {{- end }}
      redirect:
        authority: {{ .Values.redirect.to }}
{{- end }}