# Default values for service-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


domains: []

issues: le-staging

certificate:
  enable: false
  secret:
    name: ""
    annotations: {}

service:
  name: ""
  path: /
  port: 80

redirect:
  from: []
  to: ""