# Default values for service-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


domains: ['*']


certificate:
  enabled: false
  issuer: le-staging
  secret:
    name: ""
    annotations: {}

gateway:
  enabled: true
  name: ""
  https:
    port: 443
  http:
    port: 80

service:
  name: ""
  path: /
  port: 80

redirect:
  from: []
  to: ""