# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
  #pull_request:
  #  branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout chart
        uses: actions/checkout@v2
      - name: Install helm
        run: |
          curl -s -L https://get.helm.sh/helm-v3.7.0-linux-amd64.tar.gz | tar xfvz - --strip-components=1 linux-amd64/helm
          chmod 0700 helm
      - name: Running lint
        run: ./helm lint --strict ingress-chart
      - name: Checkout gh pages
        uses: actions/checkout@v2
        with:
          ref: 'gh-pages'
          path: gh-pages
      - name: Pack chart
        run: |
          ./helm package ingress-chart -d gh-pages
          ./helm repo index --url https://${GITHUB_REPOSITORY%/*}.github.io/istio-charts/ gh-pages
          ( cd gh-pages && ./index.html.sh > index.html )
      - name: Render chart to yamls
        run: |
          VERSION=$( grep ingress-chart/Chart.yaml -e '^version:' | awk '{ print $2 }' )
          mkdir -p gh-pages/yaml
          rm -rf gh-pages/yaml/${VERSION}
          ./helm template ingress-chart --output-dir gh-pages/yaml/${VERSION}
      - name: Show gh-pages changes
        run: |
          cd gh-pages
          git status
      - name: Pushing changes to gh-pages
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "Github actions"
          cd gh-pages
          git add .
          git commit -m "Automated build"
          git push
